### ISSUE TITLE
The readme suggests to install the plugin into foreman

### ISSUE THREAD

**Issue by hboetes** [theforeman/smart_proxy_monitoring#3]
It appears the readme was a copy and paste job from https://github.com/theforeman/foreman_monitoring
After asking on IRC @gwmngilfen pointed out that this plugin should be installed into foreman-proxy and not foreman.

**Comment by dgoetz** [comment]
Can explain your issue in more detail as I can not see were the readme has any copy and past from the foreman plugin? 
It also clearly tells `This plug-in adds support for Monitoring to Foreman's Smart Proxy. It requires also the Foreman Monitoring plug-in.` as the foreman plugin tells `This is a Foreman plugin for monitoring system integration. ... It requires the Smart Proxy plugin monitoring for communication with the monitoring system.`.
But if you can give my some details which parts are unclear i would be happy to expand the readme.

**Comment by hboetes** [comment]
They both point to the same installation instructions 
> See How_to_Install_a_Plugin for how to install Foreman plugins.

Since I don't know all the finer details of foreman plugins I ended up installing both in foreman, resulting in a broken database.

**Comment by dgoetz** [comment]
This is because installation is all the same for Foreman, Smart Proxy and Hammer CLI plugins.

Also installing it on the system running Foreman should be no issue, as you can always run a Smart Proxy on the same box. And it should never break the database as the Smart Proxy does not add to the database. Smart proxy is completely running from file configuration and only providing communication interface from Foreman to services.

So do you have further details on what and how it broke? As I think this should be addressed but is most likely in the wrong place here.

**Comment by hboetes** [comment]
Yes, let's leave it at that.

**Comment by GregSutcliffe** [comment]
I think this has been closed incorrectly...

| This is because installation is all the same for Foreman, Smart Proxy and Hammer CLI plugins.

That's not exactly true. While it's true if the packages exist (it's just `yum install` or `apt-get install`) it's *not* true if you're installing from Gems (core uses bundler, proxy does not) or from Source (again with bundler, but also SCL fun). This is relevant because I believe @hboetes is using Ubuntu.

In any case, the cut-paste error mentioned is here:

    * [Foreman: How to Install a Plugin](http://theforeman.org/manuals/latest/index.html#6.Plugins)

Since we have a dedicated page for the proxy plugins, that should probably link to:

    * [Foreman: How to Install a Proxy Plugin](http://projects.theforeman.org/projects/foreman/wiki/How_to_Install_a_Smart-Proxy_Plugin)

@hboetes would that satisfy? I think a link to the Proxy plugin docs is enough, right?

**Comment by hboetes** [comment]
Yes, those instructions do explain much better how to install a proxy plugin. Thanks for your assistance!
